[versions]
kotlin = "2.1.20"

fabric-loom = "1.10-SNAPSHOT"
fabric-kotlin = "1.13.2+kotlin.2.1.20"
fabric-loader = "0.16.14"

kaml = "0.73.0"

mod-publish = "0.8.4"
shadow = "8.3.+"

junit = "5.10.1"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
publish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish" }

shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[libraries]
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }

kaml = { module = "com.charleskorn.kaml:kaml-jvm", version.ref = "kaml" }

junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
fabric-loader-junit = { module = "net.fabricmc:fabric-loader-junit", version.ref = "fabric-loader" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[bundles]
junit-jupiter = [
  "junit-jupiter-engine",
  "junit-jupiter-api",
  "junit-jupiter-params",
]
